name: Build
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Build android app
        run: ./gradlew assembleDebug